import './globals.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const googleAnalytics = (
  <>
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-PEE6EPF3ZG"
    />
    <script
      dangerouslySetInnerHTML={{
        __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PEE6EPF3ZG');
  `,
      }}
    />
  </>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>{googleAnalytics}</Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
